### ISSUE TITLE
Mutex in level "A more complex thread" isn't released when it should be

### ISSUE THREAD

**Issue by petrroll** [deadlockempire/deadlockempire.github.io#34]
First mutex should get released by first thread on the 6th line and second thread should not deadlock on 4th line as a result. 
![bug](https://cloud.githubusercontent.com/assets/1764721/12798423/9f8093e4-cac9-11e5-9415-db5f446cbcd0.PNG)

**Comment by petrroll** [comment]
Isn't a bug. Didn't realize mutex is held by first thread twice and therefore must be released twice.

**Comment by Soothsilver** [comment]
Yes, not a bug _per se_, but it should be written in the Victory Text that locks must be released exactly the same number of times they are acquired.
