### ISSUE TITLE
Bug: ManualResetEventSlim.Wait method working incorrectly

### ISSUE THREAD

**Issue by kimmoyr** [deadlockempire/deadlockempire.github.io#43]
Currently in the game the ManualResetEventSlim.Wait method blocks when the ManualResetEventSlim is set/signaled. It should block when it is reset/nonsignaled.

Also the description of the Manual Reset Event challenge contains the incorrect behavior: "The Wait() method blocks if the "reset event" is "signaled" (it starts out nonsignaled).".

The tooltip for the Wait method actually contains the correct behavior: "Atomic. Blocks until the ManualResetEventSlim's state is set to 'signaled'.".

Method description from msdn: "Blocks the current thread until the current ManualResetEventSlim is set." and "The caller of this method blocks indefinitely until the current instance is set. The caller will return immediately if the event is currently in a set state."

**Comment by Soothsilver** [comment]
Thank you. Fixed.
