### ISSUE TITLE
If Statement Bug in Level "Boss Fight"?

### ISSUE THREAD

**Issue by H2CO3** [deadlockempire/deadlockempire.github.io#45]
Hi,

I believe I have found a bug in the "Boss Fight" level. I have set both global integers, `darkness` and `evil` to `1`, yet the body of the `if (darkness != 2 && evil == 2) {` statement in Thread 1 isn't entered – when I step Thread 1, control flow simply skips to the end of the block. The screenshots below are just one click of "step" away:

![screen shot 2016-02-15 at 16 03 05](https://cloud.githubusercontent.com/assets/742370/13052163/997a1c6c-d3fd-11e5-8107-c54f9daa004a.png)
![screen shot 2016-02-15 at 16 03 13](https://cloud.githubusercontent.com/assets/742370/13052164/997a2a72-d3fd-11e5-8651-1b03915d76d6.png)

Am I missing something in the evaluation of either the `if` statement or the Boolean expression, or is this indeed a bug?

Thanks!

**Comment by MichalPokorny** [comment]
:)
