### ISSUE TITLE
Some typo's and href fixes

### ISSUE THREAD

**Issue by jpluimers** [deadlockempire/deadlockempire.github.io#50]
- `System.Collections.Generic.Queue` hyperlinks don't work as they contain the inner type
- non-MSDN hyperlinks open in the same window as they miss `target='_blank'`
- "Peterson Algorithm" -> "Peterson's Algorithm" and hyperlink

These were from my investigation to see if I can make a Delphi version for the http://entwickler-konferenz.de early next week. It's going to be a challenge as this is my first real JavaScript/html code in a very long time (:

I'll keep the Delphi work in a separate branch, but will create a pull request for the other things.

**Comment by Soothsilver** [comment]
I wish you good luck, and thank you for presenting our game at the conference!

**Comment by jpluimers** [comment]
Thanks. If you have some time can you go over the changes somewhere the next weeks?

As that will influence the Delphi branch and later a "unified" branch where you can choose the language.

We need to discuss (I'm not a JavaScript UI person: this is my first non-trivial JavaScript contribute to) how a user can select the language as well (sometime like ?debug=1 would do for me on the short term).
