### ISSUE TITLE
Level 1: at 1920x1080 display is not correct for one of the tooltips

### ISSUE THREAD

**Issue by jpluimers** [deadlockempire/deadlockempire.github.io#57]
[Jacques PERE-LAPERNE](https://web.archive.org/web/20161111130327/https://plus.google.com/107251726787076664082) reported in my [G+ thread](https://web.archive.org/web/20161111130327/https://plus.google.com/+JeroenPluimers/posts/1yeNkj7jzxw):

> For information, on my screen (1920 * 1080)  the display is not correct for the toll tip ![screenshot](https://web.archive.org/web/20161111130225/https://lh3.googleusercontent.com/L1t6_rrmPceGrMTBrN4OoHRFZh-Ouei0ykzzNmd5pRQx6Qr3HzDAfBGrC8S8ey8lb7zRBwS3=w320-h180-p-rw)

Screenshot at [https://plus.google.com/u/0/photos/107251726787076664082/albums/6351652714871320289/6351652713502488546](https://web.archive.org/save/https://plus.google.com/photos/107251726787076664082/albums/6351652714871320289/6351652713502488546)

**Comment by Soothsilver** [comment]
I assume the problem here is that the tooltip is partially covered by the tutorial window.

If so, then that is a minor issue that I don't want to take the time to fix. The tooltip may be viewed in its entirety when the tutorial completes.

**Comment by jpluimers** [comment]
Agreed.
