### ISSUE TITLE
Low-pri: Arbitrary code

### ISSUE THREAD

**Issue by MichalPokorny** [deadlockempire/deadlockempire.github.io#8]
Not really in original scope and very high-effort, but adding just to keep track of this.

Some people requested editing the code. Arbitrary C# is probably unfeasible, but a limited subset might be doable.

**Comment by Soothsilver** [comment]
The game teaches concurrency. Even a limited subset of C# would better be implemented in another way and is severely out of scope. We should focus on other efforts.
